# 8 AM UTC / 3 AM ET, delete if older than 2 hours
dailyRate: cron(0 8 ? * * *)
dailyStaleAfter: 2

# Every 1 hour, delete if older than 12 hours
hourlyRate: cron(0 */1 ? * * *)
hourlyStaleAfter: 12

# Stages and statuses to retain - consistent regardless of schedule
stagesToRetain: "['PROD', 'PRODUCTION', 'AUTO', 'AUTOMATION']"
deleteableStatuses: "['CREATE_COMPLETE', 'ROLLBACK_COMPLETE', 'UPDATE_COMPLETE', 'UPDATE_ROLLBACK_COMPLETE']"

# CloudFormation output key of buckets to empty
bucketsToEmpty: "['ServerlessDeploymentBucketName']"
